OPENALEX_COL_MAP = {"project_id": "project_id",
                    "project_title": "project_title",
                    "grant_reference": "grant_reference",
                    "title": "title",
                    "abstract": "description",
                    "type": "type",
                    "doi": "doi",
                    "authors": "author",
                    "url": "url",
                    "publication_date": "year",
                    "institutions": "organisations",
                    "authors_clean": "author_clean",
                    "title_clean": "title_clean",
                    "abstract_clean": "description_clean",
                    "primary_topic": "primary_topic",
                    "primary_topic_score":"primary_topic_score",
                    "description_clean": "description_clean",
                    "subfield":"subfield",
                    "field":"field",
                    "domain":"domain"}